export default{
    home: require('../assets/home.png'),
    email: require('../assets/email.png'),
    loupe: require('../assets/loupe.png'),
    clipboard: require('../assets/clipboard.png'),
    user: require('../assets/user.png'),
    setting: require('../assets/setting.png'),
    share: require('../assets/share.png'),
    menu: require('../assets/menu.png'),
    dots: require('../assets/dots.png'), 
    back: require('../assets/back.png'),
    file: require('../assets/file.png'),
    bells: require('../assets/bells.png'),
    add: require('../assets/add.png'),
    checklist: require('../assets/checklist.png'),
    messages: require('../assets/messages.png'),
    search : require('../assets/search.png'),
    heart : require('../assets/heart.png'),
    heart1 : require('../assets/heart1.png'),
    king : require('../assets/king.png'),
    check : require('../assets/check.png'),
    close : require('../assets/close.png'),
    graphic : require('../assets/graphic.png'),
    marketing : require('../assets/marketing.png'),
    writing : require('../assets/writing.png'),
    video : require('../assets/video.png'),
    music : require('../assets/music.png'),
    programming : require('../assets/programming.png'),
    data : require('../assets/data.png'),
    business : require('../assets/business.png'),
    lifestyle : require('../assets/lifestyle.png'),
    photography : require('../assets/photography.png'),
    AI : require('../assets/AI.png'),
    angle_right : require('../assets/angle-right.png'),
    credit_card : require('../assets/credit-card.png'),
    paypal : require('../assets/paypal.png'),
    presentation: require('../assets/presentation.png'),
    goal: require('../assets/goal.png'),
    profile: require('../assets/profile.png'),
    delete: require('../assets/delete.png'),
    pen: require('../assets/pen.png'),
    send_message : require('../assets/send-message.png'),
}